sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - sudo apt-get install -y graphviz imagemagick
  - sudo pip install git+git://github.com/recast-hep/recast-backend.git@master --process-dependency-links
  - sudo pip install . --process-dependency-links

script:
  - echo 'hello world'
  - python -c 'import click;print click.__file__'
#  - sudo mkdir workdir
#  - "sudo echo 'events: 100' > ctx.yml"
#  - sudo yadage-run -t from-github/testing/busybox-flow workdir rootflow.yml
#  - docker build -t lukasheinrich/recast-cap-demo .
#  - ./testrunbackend.py rootflow.yml http://physics.nyu.edu/~lh1132/dummycomplex.zip fit.workspace.root,nonexistent,world.txt --no-cleanup -t from-github/busybox-flow
#  - find workdirs
#  - sudo rm -rf workdirs
#  -  ./testrunbackend.py rootflow.yml http://physics.nyu.edu/~lh1132/dummycomplex.zip fit.workspace.root,nonexistent,world.txt -t from-github/busybox-flow
#  - find /tmp/recast_quarantine
