sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - sudo pip install . --process-dependency-links
  - sudo apt-get install -y graphviz imagemagick
  - sudo pip install git+git://github.com/recast-hep/recast-backend.git@master --process-dependency-links

script:
  - sudo mkdir workdir
  - "sudo echo 'events: 100' > ctx.yml"
  - sudo yadage-run -t from-github/testing/busybox-flow workdir rootflow.yml
  # - sudo yadage-run -t from-github workdir pheno_workflows/madgraph_delphes.yml ctx.yml
  # - sudo ls -lrt workdir
  # - sudo rm -rf workdir
  # - sudo ./runtest.sh
  - "sudo RECAST_CAP_TOPLVL='from-github/testing/busybox-flow' ./testrunbackend.py rootflow.yml http://physics.nyu.edu/~lh1132/dummycomplex.zip fit.workspace.root,nonexistent,world.txt --no-cleanup"
  - find workdirs
  - sudo rm -rf workdirs
  - "sudo RECAST_CAP_TOPLVL='from-github/testing/busybox-flow' ./testrunbackend.py rootflow.yml http://physics.nyu.edu/~lh1132/dummycomplex.zip fit.workspace.root,nonexistent,world.txt"
  - find /tmp/recast_quarantine
  