sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - "pip install git+git://github.com/lukasheinrich/adage.git@master"
  - "pip install git+git://github.com/lukasheinrich/yadage.git@master"
  - "pip install git+git://github.com/lukasheinrich/packtivity.git@master"
  - "pip install ."
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y imagemagick

script:
  - mkdir workdir
  - "echo 'events: 100' > ctx.yml"
  - yadage-run -t from-github workdir pheno_workflows/madgraph_delphes.yml ctx.yml
  - ls -lrt workdir
  - rm -rf workdir
  - ./runtest.sh
