sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - "pip install git+git://github.com/lukasheinrich/adage.git@master"
  - "pip install ."
  - apt-get install -y graphviz
  - apt-get install -y imagemagick

script:
  - docker pull busybox 
  - docker run -it busybox echo 'hello'
  - mkdir workdir
  - recastworkflow-capsteer workdir pheno_workflows/madgraph_delphes.yml tests/phenoctx.yml
  - ls -lrt workdir
