sudo: required
services:
- docker
language: python
python:
- '2.7'
install:
- sudo apt-get install -y graphviz imagemagick
- pip install git+git://github.com/recast-hep/recast-backend.git@master --process-dependency-links
- pip install . --process-dependency-links
script:
- 'echo ''events: 100'' > ctx.yml'
- yadage-run -t from-github/testing/busybox-flow workdir rootflow.yml
- RECAST_PLUGIN_TRACK=false ./testrunbackend.py rootflow.yml http://physics.nyu.edu/~lh1132/dummycomplex.zip
  fit.workspace.root,nonexistent,world.txt --no-cleanup -t from-github/testing/busybox-flow
- find workdirs
- rm -rf workdirs
- RECAST_PLUGIN_TRACK=false ./testrunbackend.py rootflow.yml http://physics.nyu.edu/~lh1132/dummycomplex.zip
  fit.workspace.root,nonexistent,world.txt -t from-github/testing/busybox-flow
- find /tmp/recast_quarantine
- docker build -t recast/yadage-worker:githead .
- echo $DOCKERLOGIN
- docker login -u $DOCKERLOGIN -p $DOCKERPW
- docker push recast/yadage-worker:githead
env:
  global:
  - secure: 1MGMlWOlfdQ6GNJAvh0H0DyQXrIP7B1ZDzLVzBrCNEIE+qiYC2QBLs+8zBAoNTA8Mra2l3RJPUYhPnAPD67isuI74bj0WpsFzyxn1Dzy9/yct/mMmpOUyDYGkFxxM/nMagTaznjlx+2gA7sk9UK75a36aRncsB96P5zIkgs+C7HOh+XvXeuhdth05J8K04WUKvW0N4V3ahQfM33NlAABMy3QA3RcQBURuwW1AxKbYnTiw/3piSqaQZsqwGRZ/kKU7xqIAnhLduaNXxp74DfXBdqzTnJkVRGY3FHRIW/S/MCVV+uQMeD0qByru6BInIb2FxWYrUjK5/bFc/U01Af4mB5MVlxz44mw9ZRy0SGgHhJS7ebckvZ+q+GV1Od46y7GGyJqhJyU3UA6HBYuRDZmnXHbaJd5HlMYlGT9OGovFj0FFVVwpV8WpppefcWQ3HwrgNi9Q3nI+YyJOhAASR1sui8S+vslAYE7s83NOhQkB6xiOJGu7j6EZU7RmBhkafHW1hKZQWZQn3/8LWSUPt1kaI3qGI1ACkZ6sIkV6wcaT23h4mgYHZjOsCI/z6KiJqTm0Dyv+jK/n2Oc5m6xEStv5K1Z23RsTSpgQklvdsxyKWpZo2polnh75JCu4PUh57peTnqMnd/qVTsUMBkMriUNV5lRXUo6SImj0Xj09IhTLCY=
  - secure: tc2LQuXVwfPO+PSMPs4bXgzKf+/zU+vFY7cHBoPAwK1S589eF3grnrU1y/StR3K+wP3bpYJRDCfT1FThhUpLTNPn+FCpoDuSUY88QG2vWvL9FWi2SB49PSedOI5AZcx/7OghiIcOsAGJLKa+6X5f6YMUStO+yr4Rn6J8IMUr8WiLTmfgRWJOuORNgT92+jzH6LPCw7EO8kwxSnPRNH4e/+0cQRzeL8gQZ6QZcjCkHXxK5A5bX6k8R0U2YCa6247UcPzqv0S4Hu6AfiaAiiWmOF6HqMBKVzk9tudVgjGRA+CmYUd86DAXJ9dMqimiMCozsgobLl6meF6s+krFzNI2ppJ5Zg0V1xlLZSxXB0Mgjq65+xghlap2hvoPWe/MqCvv2NSQ9NxESfEDUKAbiFlcmJGV7Yk0luEmQnXWEPsduBbTsdZJnqn9+no4pKj+Fk2WpLtokXIpczVLTyZ/AlgYSB6OehLz3H94fcGp80to6IrRNtshurIW1it29mXj/TirjrXAZvW1fOHqtom4fSyHqMw4Avp5g5z7Jx+OM7JwmTsfw4evX4/jp3XHuf9J31gvaxX2r2j3TEe6+A2sZEdgpMiam90+bgIlz2S5IMLmcZmyK0EESqGXMF1RYMrK2iBCjHm4U6WDAteLWhAUikN6atsU4T/gjpD+L0GRBgwSpqU=
