sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - "pip install git+git://github.com/lukasheinrich/adage.git@master"
  - "pip install ."
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y imagemagick

script:
  - docker pull busybox 
  - docker run -it busybox echo 'hello'
  - mkdir workdir_madgraph_delphes
  - recastworkflow-capsteer workdir_madgraph_delphes pheno_workflows/madgraph_delphes.yml tests/phenoctx.yml
  - ls -lrt workdir_madgraph_delphes
  - mkdir workdir_dummy_complex
  - recastworkflow-capsteer workdir_dummy_complex dummy_analysis/complex_mapreduce.yml dummycontext.yml
  - ls -lrt workdir_dummy_complex
