sudo: required
services:
- docker
language: python
python:
- '2.7'
install:
- sudo apt-get install -y graphviz imagemagick
- pip install git+git://github.com/recast-hep/recast-backend.git@master --process-dependency-links
- pip install . --process-dependency-links
script:
- 'echo ''events: 100'' > ctx.yml'
- yadage-run -t from-github/testing/busybox-flow workdir rootflow.yml
- RECAST_PLUGIN_TRACK=false ./testrunbackend.py rootflow.yml http://physics.nyu.edu/~lh1132/dummycomplex.zip
  fit.workspace.root,nonexistent,world.txt --no-cleanup -t from-github/testing/busybox-flow
- find workdirs
#- rm -rf workdirs
#- RECAST_PLUGIN_TRACK=false ./testrunbackend.py rootflow.yml http://physics.nyu.edu/~lh1132/dummycomplex.zip
#  fit.workspace.root,nonexistent,world.txt -t from-github/testing/busybox-flow
#- find /tmp/recast_quarantine
- docker pull cern/cc7-base
- docker build -t "recast/yadage-worker:git-${TRAVIS_BRANCH}" .
- echo $DOCKERLOGIN
- docker login -u $DOCKERLOGIN -p $DOCKERPW
- docker push "recast/yadage-worker:git-${TRAVIS_BRANCH}"
env:
  global:
  - secure: tZT+9iWK1FyrD1KWQ3GCe8pVd3m7xO7YqYZaqY8lWCSKEPXxUNl9hONcBDpicKnFwaEcDE/1oP4JIOolxNHeYhUVtfNN/y+odZGcgNPgrM3/NGb4WXEFGPJQNTlj4hrjBq/neZX+ZgXW73HbtJtXYsltN046rAeYWlyqE/iA1UsosEIrkz0VWwWyI7EMePK7YdpudwqNGVYWfakxTkh2gHiZesd44J0LGLkgQoTkJpAY82o9p5fXjvZd0tZuwPosjZP/BHqjc2myokioRavSsUO0USElIRmc5IflwLuS5H7t9jwBeevncFpEsSYbmdbnFEzlp6UoTVZ//NATbPcfHfrdVs37PTWQbw2XAQhh8q/zvfwo6lKW6jAG8Ywu4qVA8SRei78+/acsin3y5K1hnw8g1QVWK7RtZjiNp89dtibhzgCiABar9LtYMmLZflfsnzZ48kUGxlcxdgR8ExyflHKrd+21cI82bDZEcANFZYX+GbxaSVBiRqoJ+P0L13Qu73d9wGvc3nMyfGFhzB/Bdsh610iLchvNBxGJ2xJEqtNeENkZwrCP0vSN1HIQWnNiZohoSo6xv2KT+vadE6degPfw+fmUpZypdOu2J8TKgcTeWA3K4TEJZDw87W4E6Qa03g8Hr3Ar2Vp+EvvkRglUvgrygnA4Aqn2LhkNm/MVF2s=
  - secure: P1iF6kDkFDBlUJZHIwJmE6uOCj0ZEen9Yh6LfhcLn1jFhbN1Po4mb0hYCpdzcbf6G58KDbtlUXixwPAtEzrQiJTZ4P1V9Y0nlKzO4KsTQD6SZOOv3DFfOylOA8L7wTCffZmELZbJ81pAvrPKe0gSuEtxY+ZrOc2N4p3AEjJNXTSag+XopuD+zHFsC8FJnv0a4qoxb4luL2JzgtJ17Csz1VcHaRzIjW2iIKEZPrSZ20HkeVPClfZzfLTgHVO6gr05xsg/q0naLudP1X8Q/H5ERwfNgdw9aYsoa8YwpDl82l99uttcy85f7nUm2OxFBDMTrDt7C+zWhRnNEOQlwEIUbgMC4wkpwIeb5EdlDCCGyxZEuJVod6ePNP2SupWAwBySfI9DF/ZZjt0KUv8mJj7GZmtrRr4AINZ6ykTXaNI0l0+qZq1N2tiE6exnIpYBLji9OVN8CbXwwBmnOVEmn1xwcE4jqrSXGCRqpFUlMJW+E3QjusZngFPNjVv82fwZfg0OCVBJIguf9+UOM3+Xsx+y4AWHV+xAioXu6u6bgDmE8rz/218YGbShmDVJxVyDF7C88BuC4uBvUuGfWrDW1ygCWJSLrBNfLjhLU/OIbT0YyKaB9j23g0CnRWsnR6fC7+zGTGuYLb4tvBZ6cyr2uKGqcL2YLbxicsfCwGCpIh3NagQ=
