stages:
  - name: upstream
    scheduler:
      scheduler_type: jq-stage
      stepscript: >
        [.]
      workflow: null
      bindings: null
  - name: downstream
    dependencies: ['upstream']
    scheduler:
      scheduler_type: singlestep-stage
      parameters: null
      workflow: null