context:
  dataset_data: ~
  dataset_mcback_one: ~
  dataset_mcback_two: ~
  signal_par_one: ~
  signal_par_two: ~
  data_driven_cut: ~
stages:
  - name: preparedata
    parameters:
      inputtype: 'data'
      input: '{dataset_data}'
      output: '{dataset_data}.ntup.root'
    scheduler:
      scheduler-type: 'singlestep-from-context'
      steps:
        single: {$ref: 'complex_analysis/ntupling.yml'}
  - name: mcback1
    parameters:
      inputtype: 'mc'
      input: '{dataset_mcback_one}'
      output: '/workdir/{dataset_mcback_one}.ntup.root'
    scheduler:
      scheduler-type: 'singlestep-from-context'
      steps:
        single: {$ref: 'complex_analysis/ntupling.yml'}
  - name: mcback2
    parameters:
      inputtype: 'mc'
      input: '{dataset_mcback_one}'
      output: '/workdir/{dataset_mcback_one}.ntup.root'
    scheduler:
      scheduler-type: 'singlestep-from-context'
      steps:
        single: {$ref: 'complex_analysis/ntupling.yml'}
  - name: acquire_signal
    parameters:
      par_one: '{signal_par_one}'
      par_two: '{signal_par_two}'
      output: '/workdir/signal.input.root'
    scheduler:
      scheduler-type: 'singlestep-from-context'
      steps:
        single: {$ref: 'complex_analysis/getsignal.yml'}
  - name: mcsignal
    dependencies:
      - acquire_signal
    parameters:
      inputtype: 'mc'
      output: '/workdir/signal.ntup.root'
    scheduler:
      scheduler-type: 'reduce-from-dep-output'
      steps:
        reduce: {$ref: 'complex_analysis/ntupling.yml'}
      from_stages:
        - acquire_signal
      take_outputs: signal_sample
      to_input: input
  - name: hist_mcsignal
    dependencies:
      - mcsignal
    parameters:
      output: '/workdir/signal.histos.root'
    scheduler:
      scheduler-type: 'reduce-from-dep-output'
      steps:
        reduce: {$ref: 'complex_analysis/makehistos_mc.yml'}
      from_stages:
        - mcsignal
      take_outputs: ntuple
      to_input: input
  - name: hist_mc1
    dependencies:
      - mcback1
    parameters:
      output: '/workdir/back1.histos.root'
    scheduler:
      scheduler-type: 'reduce-from-dep-output'
      steps:
        reduce: {$ref: 'complex_analysis/makehistos_mc.yml'}
      from_stages:
        - mcback1
      take_outputs: ntuple
      to_input: input
  - name: hist_mc2
    dependencies:
      - mcback2
    parameters:
      output: '/workdir/back2.histos.root'
    scheduler:
      scheduler-type: 'reduce-from-dep-output'
      steps:
        reduce: {$ref: 'complex_analysis/makehistos_mc.yml'}
      from_stages:
        - mcback2
      take_outputs: ntuple
      to_input: input
  - name: hist_data
    dependencies:
      - preparedata
    parameters:
      output: '/workdir/data.histos.root'
    scheduler:
      scheduler-type: 'reduce-from-dep-output'
      steps:
        reduce: {$ref: 'complex_analysis/makehistos_data.yml'}
      from_stages:
        - preparedata
      take_outputs: ntuple
      to_input: input
  - name: data_driven_back_hists
    dependencies:
      - preparedata
    parameters:
      output_loose: '/workdir/data.histos.root:/hist_loose'
      output_tight: '/workdir/data.histos.root:/tight_hist'
      tight_cut: '{data_driven_cut}'
    scheduler:
      scheduler-type: 'reduce-from-dep-output'
      steps:
        reduce: {$ref: 'complex_analysis/makehistos_datadrivenback.yml'}
      from_stages:
        - preparedata
      take_outputs: ntuple
      to_input: input
  - name: hist_estimate
    dependencies:
      - data_driven_back_hists
    parameters:
      estimate_output: '/workdir/estimate.hist.root'
    scheduler:
      scheduler-type: 'zip-from-dep-output'
      steps:
        single: {$ref: 'complex_analysis/estimate_back.yml'}
      zip:
        - outputs: 'tight'
          zip_with: ['tighthisto']
          from_stages:
            - data_driven_back_hists
        - outputs: 'loose'
          zip_with: ['loosehisto']
          from_stages:
            - data_driven_back_hists
  - name: fit
    dependencies:
      - hist_estimate
      - hist_data
      - hist_mc1
      - hist_mc2
      - hist_mcsignal
    parameters:
      fitresults: /workdir/fitresults.yaml
      workspace: /workdir/fit.workspace.root
    scheduler:
      scheduler-type: 'zip-from-dep-output'
      steps:
        single: {$ref: 'complex_analysis/runfit.yml'}
      zip:
        - outputs: 'estimate|mchistos'
          zip_with: ['back1','back2','back3']
          from_stages:
            - hist_mc1
            - hist_mc2
            - hist_estimate
        - outputs: 'mchisto'
          zip_with: ['signal']
          from_stages:
            - hist_mcsignal
        - outputs: 'datahistos'
          zip_with: ['data']
          from_stages:
            - hist_data
  - name: plots
    dependencies:
      - hist_estimate
      - hist_data
      - hist_mc1
      - hist_mc2
      - hist_mcsignal
    parameters:
      plotdir: /workdir/plots
    scheduler:
      scheduler-type: 'zip-from-dep-output'
      steps:
        single: {$ref: 'complex_analysis/makeplots.yml'}
      zip:
        - outputs: 'estimate|mchistos'
          zip_with: ['back1','back2','back3']
          from_stages:
            - hist_mc1
            - hist_mc2
            - hist_estimate
        - outputs: 'mchisto'
          zip_with: ['signal']
          from_stages:
            - hist_mcsignal
        - outputs: 'datahistos'
          zip_with: ['data']
          from_stages:
            - hist_data
