context:
  inputdatasets: ~
stages:
  - name: data_acquisition
    parameters:
      inputs: '{inputdatasets}'
    scheduler:
      scheduler-type: 'singlestep-from-context'
      steps:
        single: {$ref: 'lhcb_talk/dataacquisition.yml'} 
  - name: mapstage
    dependencies:
      - data_acquisition
    parameters:
      output: 'output_{index}'
    scheduler:
      scheduler-type: 'map-from-dep-output'
      steps:
        map: {$ref: 'lhcb_talk/mappingstep.yml'}
      from_stages: data_acquisition
      take_outputs: acq_out
      to_input: input
      stepname: 'mapstep_{index}'
  - name: reduce
    dependencies:
      - mapstage
    parameters:
      out: mergedfile.root
    scheduler:
      scheduler-type: 'reduce-from-dep-output'
      steps:
        reduce: {$ref: 'lhcb_talk/reducestep.yml'}
      from_stages:
        - mapstage
      take_outputs: map.*
      to_input: in